package com.xshell.xshelllib.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_UPDATE".
 */
public class AppUpdate {

    private Long id;
    private String appName;
    private String localVersion;

    public AppUpdate() {
    }

    public AppUpdate(Long id) {
        this.id = id;
    }

    public AppUpdate(Long id, String appName, String localVersion) {
        this.id = id;
        this.appName = appName;
        this.localVersion = localVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getLocalVersion() {
        return localVersion;
    }

    public void setLocalVersion(String localVersion) {
        this.localVersion = localVersion;
    }

}
