package com.xshell.xshelllib.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HINT".
 */
public class Hint {

    private Long id;
    private int usrId;
    private String type;
    private String targetId;
    private Integer unReadCount;
    private String lastMessage;
    private String lastReadTime;
    private String localMessageTime;

    public Hint() {
    }

    public Hint(Long id) {
        this.id = id;
    }

    public Hint(Long id, int usrId, String type, String targetId, Integer unReadCount, String lastMessage, String lastReadTime, String localMessageTime) {
        this.id = id;
        this.usrId = usrId;
        this.type = type;
        this.targetId = targetId;
        this.unReadCount = unReadCount;
        this.lastMessage = lastMessage;
        this.lastReadTime = lastReadTime;
        this.localMessageTime = localMessageTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUsrId() {
        return usrId;
    }

    public void setUsrId(int usrId) {
        this.usrId = usrId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTargetId() {
        return targetId;
    }

    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    public Integer getUnReadCount() {
        return unReadCount;
    }

    public void setUnReadCount(Integer unReadCount) {
        this.unReadCount = unReadCount;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public String getLastReadTime() {
        return lastReadTime;
    }

    public void setLastReadTime(String lastReadTime) {
        this.lastReadTime = lastReadTime;
    }

    public String getLocalMessageTime() {
        return localMessageTime;
    }

    public void setLocalMessageTime(String localMessageTime) {
        this.localMessageTime = localMessageTime;
    }

}
