package com.xshell.xshelllib.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XLOG".
 */
public class XLog {

    private Long id;
    private String data;

    public XLog() {
    }

    public XLog(Long id) {
        this.id = id;
    }

    public XLog(Long id, String data) {
        this.id = id;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
